# Generated by Django 5.2.5 on 2026-07-19 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_sucursal_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='propietario',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_propias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='sucursales_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
