# Generated by Django 5.2.5 on 2026-07-19 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='propietario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_propias', to=settings.AUTH_USER_MODEL),
        ),
    ]
