# Generated by Django 5.2.5 on 2026-07-19 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0004_alter_sucursal_propietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: SUR16, SUR20, SUR24', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('propietario', 'nombre'), name='unique_sucursal_por_propietario'),
        ),
    ]
