# Generated by Django 5.2.5 on 2026-07-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sueldo_semanal',
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_periodo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_nomina',
            field=models.CharField(choices=[('SEMANA', 'Lunes a Viernes'), ('FIN_SEMANA', 'Sábado y Domingo')], default='SEMANA', max_length=20),
        ),
    ]
