# Generated by Django 5.2.5 on 2026-08-20 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_remove_empleado_sueldo_semanal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagonomina',
            options={},
        ),
        migrations.RemoveField(
            model_name='pagonomina',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='pagonomina',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='pagonomina',
            name='fecha_inicio',
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='nomina.empleado')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.AddField(
            model_name='pagonomina',
            name='nomina',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='nomina.nomina'),
        ),
        migrations.AddConstraint(
            model_name='nomina',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha_inicio', 'fecha_fin'), name='nomina_unica_por_periodo'),
        ),
    ]
