# Generated by Django 5.2.5 on 2026-08-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sucursal',
        ),
    ]
