# Generated by Django 5.2.5 on 2026-08-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='producto',
            name='contenido_pzas',
            field=models.PositiveIntegerField(default=0, help_text='Pzas que contiene la caja'),
        ),
    ]
