# Generated by Django 5.2.5 on 2026-08-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_existencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='contenido_pzas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
