# Generated by Django 5.2.5 on 2026-08-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_producto_contenido_pzas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='registrar_venta_diaria',
            field=models.BooleanField(default=True, help_text='Indica si sus variantes se muestran en el registro diario de ventas.'),
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='inventario.producto')),
            ],
            options={
                'ordering': ['producto__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'nombre'), name='unique_variante_producto')],
            },
        ),
    ]
