# Generated by Django 5.2.5 on 2026-08-26 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_registrar_venta_diaria_varianteproducto'),
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes_producto', to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_diarios', to='sucursales.sucursal')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_diarios', to='inventario.varianteproducto')),
            ],
            options={
                'ordering': ['variante__producto__nombre', 'variante__nombre'],
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'fecha', 'variante'), name='unique_inventario_diario')],
            },
        ),
    ]
