# Generated by Django 5.2.5 on 2026-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_varianteproducto_producto_inventariodiario'),
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariodiario',
            options={'ordering': ['-fecha', 'variante__producto__nombre', 'variante__nombre']},
        ),
        migrations.RemoveConstraint(
            model_name='inventariodiario',
            name='unique_inventario_diario',
        ),
        migrations.AddIndex(
            model_name='inventariodiario',
            index=models.Index(fields=['sucursal', 'fecha'], name='inventario__sucursa_d08fd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventariodiario',
            constraint=models.UniqueConstraint(fields=('sucursal', 'variante', 'fecha'), name='unique_inventario_diario'),
        ),
    ]
