# Generated by Django 5.2.5 on 2026-09-25 21:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_inventariodiario_options_and_more'),
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['variante_vendida__producto__nombre', 'variante_vendida__nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad consumida del insumo por 1 unidad vendida.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['insumo__producto__nombre', 'insumo__nombre'],
            },
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('inventario_inicial', 'Inventario inicial'), ('compra', 'Compra'), ('ajuste_entrada', 'Ajuste entrada'), ('ajuste_salida', 'Ajuste salida'), ('venta', 'Consumo por venta'), ('merma', 'Merma'), ('traslado_entrada', 'Traslado entrada'), ('traslado_salida', 'Traslado salida')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Guardar siempre como valor positivo.', max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='sucursales.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='inventario.varianteproducto')),
            ],
            options={
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
