# Generated by Django 5.2.5 on 2026-09-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_receta_recetadetalle_varianteproducto_precio_venta_and_more'),
        ('ventas', '0005_venta_ventadetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='ventas.ventadetalle'),
        ),
        migrations.AddField(
            model_name='receta',
            name='variante_vendida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receta', to='inventario.varianteproducto'),
        ),
        migrations.AddField(
            model_name='recetadetalle',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas_como_insumo', to='inventario.varianteproducto'),
        ),
        migrations.AddField(
            model_name='recetadetalle',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.receta'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['sucursal', 'fecha_hora'], name='inventario__sucursa_32a0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['variante', 'fecha_hora'], name='inventario__variant_082700_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo', 'fecha_hora'], name='inventario__tipo_6a14e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='recetadetalle',
            constraint=models.UniqueConstraint(fields=('receta', 'insumo'), name='unique_insumo_por_receta'),
        ),
    ]
