# Generated by Django 5.2.5 on 2026-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_movimientoinventario_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('terminado', 'Producto terminado'), ('insumo', 'Insumo'), ('ambos', 'Ambos')], default='terminado', max_length=20),
        ),
    ]
