# Generated by Django 5.2.5 on 2026-10-02 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_producto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodiario',
            name='cantidad_teorica',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventariodiario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_diarios_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventariodiario',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
