# Generated by Django 5.2.5 on 2026-10-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_inventariodiario_cantidad_teorica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodiario',
            name='cantidad_teorica',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
