# Generated by Django 5.2.5 on 2026-10-04 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_inventariodiario_cantidad_teorica'),
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventariodiario',
            name='unique_inventario_diario',
        ),
        migrations.AddConstraint(
            model_name='inventariodiario',
            constraint=models.UniqueConstraint(fields=('sucursal', 'variante', 'fecha'), name='unique_inventario_sucursal_fecha_variante'),
        ),
    ]
