# Generated by Django 5.2.5 on 2026-10-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_inventariodiario_unique_inventario_diario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariodiario',
            name='consumo_teorico',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
