# Generated by Django 5.2.5 on 2026-10-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_inventariodiario_consumo_teorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='momento_consumo',
            field=models.CharField(choices=[('venta', 'Al vender'), ('preparacion', 'Al preparar')], default='venta', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('inventario_inicial', 'Inventario inicial'), ('compra', 'Compra'), ('ajuste_entrada', 'Ajuste entrada'), ('ajuste_salida', 'Ajuste salida'), ('venta', 'Consumo por venta'), ('merma', 'Merma'), ('traslado_entrada', 'Traslado entrada'), ('traslado_salida', 'Traslado salida'), ('produccion_entrada', 'Producto preparado'), ('produccion_salida', 'Consumo por preparación')], max_length=30),
        ),
    ]
