# Generated by Django 5.2.5 on 2026-10-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_receta_momento_consumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='controlar_inventario',
            field=models.BooleanField(default=False, help_text='Indica si las variantes de este producto se incluyen en el conteo físico de inventario.'),
        ),
    ]
