# Generated by Django 5.2.5 on 2026-10-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_producto_controlar_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo_merma',
            field=models.CharField(blank=True, choices=[('roto', 'Roto'), ('caducidad', 'Caducidad'), ('preparacion_fallida', 'Preparación fallida'), ('otro', 'Otro')], max_length=30, null=True),
        ),
    ]
