# Generated by Django 5.2.5 on 2026-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_movimientoinventario_motivo_merma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo_merma',
            field=models.CharField(blank=True, choices=[('roto', 'Roto'), ('caducidad', 'Caducidad'), ('traslado_sucursal', 'Traslado a otra sucursal'), ('robo', 'Robo'), ('preparacion_fallida', 'Preparación fallida'), ('otro', 'Otro')], max_length=30, null=True),
        ),
    ]
