# Generated by Django 5.2.5 on 2026-07-05 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagocuentaporpagar',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='pagocuentaporpagar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 5, 18, 55, 15, 443054, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
