# Generated by Django 5.2.5 on 2026-07-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_pagocuentaporpagar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='saldo',
        ),
    ]
