# Generated by Django 5.2.5 on 2026-07-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_remove_cuentaporpagar_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='estatus',
        ),
    ]
