# Generated by Django 5.2.5 on 2026-07-22 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_remove_cuentaporpagar_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to='compras.cuentaporpagar')),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.pagocuentaporpagar')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
