# Generated by Django 5.2.5 on 2026-08-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_proveedor_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionpago',
            name='pago',
        ),
        migrations.AddField(
            model_name='pagocuentaporpagar',
            name='programacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='compras.programacionpago'),
        ),
        migrations.AddField(
            model_name='programacionpago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagocuentaporpagar',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='compras.cuentaporpagar'),
        ),
        migrations.AlterField(
            model_name='pagocuentaporpagar',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagocuentaporpagar',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programacionpago',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='compras.cuentaporpagar'),
        ),
        migrations.AlterField(
            model_name='programacionpago',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
