# Generated by Django 5.2.5 on 2026-08-24 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_remove_programacionpago_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuentaporpagar',
            name='programacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='compras.programacionpago'),
        ),
    ]
