# Generated by Django 5.2.5 on 2026-10-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0018_alter_movimientoinventario_motivo_merma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('precio_grupo', 'Precio por grupo'), ('descuento_grupo', 'Descuento por grupo'), ('descuento_unidad', 'Descuento por unidad')], max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=True)),
                ('domingo', models.BooleanField(default=True)),
                ('precio_grupo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento_por_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromocionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='promociones.promocion')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones', to='inventario.varianteproducto')),
            ],
        ),
    ]
