# Generated by Django 5.2.5 on 2026-10-09 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_movimientoinventario_motivo_merma'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promociondetalle',
            name='variante',
        ),
        migrations.AddField(
            model_name='promociondetalle',
            name='cualquier_variante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promociondetalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_promocion', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='promociondetalle',
            name='variantes_elegibles',
            field=models.ManyToManyField(blank=True, related_name='detalles_promocion', to='inventario.varianteproducto'),
        ),
    ]
