# Generated by Django 5.2.5 on 2026-06-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos', '0003_remove_gasto_periodo_gasto_fecha'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_pago', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='sucursales.sucursal')),
            ],
        ),
    ]
