# Generated by Django 5.2.5 on 2026-06-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_remove_gasto_periodo_gasto_fecha'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gasto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_servicio', to='gastos.gasto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='servicios.serviciorecurrente')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
