# Generated by Django 5.2.5 on 2026-08-04 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.BooleanField(default=False)),
                ('ventas', models.BooleanField(default=False)),
                ('finanzas', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('nomina', models.BooleanField(default=False)),
                ('administracion', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
