# Generated by Django 5.2.5 on 2026-06-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('periodo', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='ventas.periodosemanal')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursal')),
            ],
        ),
    ]
