# Generated by Django 5.2.5 on 2026-06-04 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
        ('ventas', '0002_remove_ventasemanal_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='periodo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='ventas.resumensemanal'),
        ),
    ]
