# Generated by Django 5.2.5 on 2026-06-04 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gasto_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='periodo',
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
