# Generated by Django 5.2.5 on 2026-06-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_remove_gasto_periodo_gasto_fecha'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='pago_nomina',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.pagonomina'),
        ),
    ]
