# Generated by Django 5.2.5 on 2026-06-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_categoria_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
