# Generated by Django 5.2.5 on 2026-07-19 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_gasto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
