# Generated by Django 5.2.5 on 2026-09-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_gasto_created_at_gasto_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='gastos/comprobantes/%Y/%m/'),
        ),
    ]
