# Generated by Django 5.2.5 on 2026-09-23 22:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Snapshot JSON del reporte mensual.')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('generado_en', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha/hora en que se generó o regeneró el snapshot actual.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_mensuales_generados', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_mensuales', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, help_text='NULL representa un reporte consolidado de todas las sucursales del propietario.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_mensuales', to='sucursales.sucursal')),
            ],
            options={
                'verbose_name': 'Reporte mensual',
                'verbose_name_plural': 'Reportes mensuales',
                'ordering': ['-anio', '-mes', 'sucursal__nombre'],
                'indexes': [models.Index(fields=['propietario', 'anio', 'mes'], name='reportes_re_propiet_88c2fb_idx'), models.Index(fields=['sucursal', 'anio', 'mes'], name='reportes_re_sucursa_c742aa_idx'), models.Index(fields=['generado_en'], name='reportes_re_generad_8d1f5f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='reporte_mensual_mes_valido'), models.CheckConstraint(condition=models.Q(('anio__gte', 2000), ('anio__lte', 2100)), name='reporte_mensual_anio_valido'), models.UniqueConstraint(condition=models.Q(('sucursal__isnull', False)), fields=('propietario', 'sucursal', 'anio', 'mes'), name='uniq_reporte_mensual_propietario_sucursal_periodo'), models.UniqueConstraint(condition=models.Q(('sucursal__isnull', True)), fields=('propietario', 'anio', 'mes'), name='uniq_reporte_mensual_propietario_consolidado_periodo')],
            },
        ),
    ]
