# Generated by Django 5.2.5 on 2026-09-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportemensual',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
