# Generated by Django 5.2.5 on 2026-06-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='VentaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.periodosemanal')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursal')),
            ],
        ),
    ]
