# Generated by Django 5.2.5 on 2026-06-04 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasemanal',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='ventasemanal',
            name='sucursal',
        ),
        migrations.CreateModel(
            name='ResumenSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes', to='sucursales.sucursal')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
