# Generated by Django 5.2.5 on 2026-06-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gasto_periodo'),
        ('ventas', '0002_remove_ventasemanal_periodo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodoSemanal',
        ),
        migrations.DeleteModel(
            name='VentaSemanal',
        ),
        migrations.AddConstraint(
            model_name='resumensemanal',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha_inicio', 'fecha_fin'), name='unique_resumen_semanal'),
        ),
    ]
