# Generated by Django 5.2.5 on 2026-09-25 21:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_receta_recetadetalle_varianteproducto_precio_venta_and_more'),
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_nombre_and_more'),
        ('ventas', '0004_ventadiaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='confirmada', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de la venta pagado en efectivo.', max_digits=12)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de la venta pagado con tarjeta.', max_digits=12)),
                ('monto_recibido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dinero recibido del cliente. Usar solo cuando el método sea efectivo.', max_digits=12)),
                ('cambio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='sucursales.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('variante_nombre', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.varianteproducto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sucursal', 'fecha_hora'], name='ventas_vent_sucursa_6e287f_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha_hora'], name='ventas_vent_estado_d69a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['metodo_pago', 'fecha_hora'], name='ventas_vent_metodo__77d751_idx'),
        ),
        migrations.AddConstraint(
            model_name='ventadetalle',
            constraint=models.UniqueConstraint(fields=('venta', 'variante'), name='unique_variante_por_venta'),
        ),
    ]
