# Generated by Django 5.2.5 on 2026-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_ventadetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadiaria',
            name='otro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
