# Generated by Django 5.2.5 on 2026-10-08 20:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
        ('ventas', '0006_ventadiaria_otro'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('precio_grupo', 'Precio por grupo'), ('descuento_grupo', 'Descuento por grupo'), ('descuento_unidad', 'Descuento por unidad')], max_length=30)),
                ('cantidad_aplicaciones', models.PositiveIntegerField(default=1)),
                ('descuento_por_aplicacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promociones.promocion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones_aplicadas', to='ventas.venta')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('venta', 'promocion'), name='unique_promocion_por_venta')],
            },
        ),
    ]
