# Generated by Django 5.2.5 on 2026-10-09 21:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_sucursal_propietario_alter_sucursal_nombre_and_more'),
        ('ventas', '0007_ventapromocion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ventadiaria',
            name='unique_venta_diaria',
        ),
        migrations.AddField(
            model_name='ventadiaria',
            name='efectivo_contado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ventadiaria',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ventadiaria',
            name='tipo_registro',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='ventadiaria',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha'), name='unique_venta_diaria_sucursal_fecha'),
        ),
    ]
